### ISSUE TITLE
showing points with multiple sport values, if one of them is climbing...

### ISSUE THREAD

**Issue by C-Makridis** [MartinKoeller/ClimbingMap#1]
I hope I'm not reporting this at the wrong project...

If I understand correctly, this code is used for http://openclimbingmap.bstegmaier.de.

If that is the case, I noticed, that points / areas / ways with multiple values for the sport tag, are not renderd, even though one of the given values is "climbing".

This mostly affects clubs and indoor facilities.

As an example, see http://www.openstreetmap.org/way/244450997 and http://www.openstreetmap.org/node/4004954689

Both examples have climbing among their sport tag values, neither of them is shown in http://openclimbingmap.bstegmaier.de/#18/38.07159/23.73883 and http://openclimbingmap.bstegmaier.de/#18/37.91285/23.73619

According to OpenStreetMaps wiki 

> Where a number of sports are associated with a single feature then separate the sports with a ';', for example 'gymnastics;badminton'.

Thank you for your time, and please forgive me if this problem does not affect this project.

**Comment by MartinKoeller** [comment]
Sorry, you are at the wrong project. This is not the code for used for http://openclimbingmap.bstegmaier.de.

**Comment by C-Makridis** [comment]
I'm so sorry for the inconvenience :)
